const {test,expect}=require('@playwright/test');
const baseURL=process.env.E2E_BASE_URL||'http://localhost/ophytrak';
const carrierEmail=process.env.E2E_CARRIER_EMAIL||'qa.carrier.20260806carrier1@example.test';
const deliveryEmail=process.env.E2E_CARRIER_DELIVERY_EMAIL||'qa.carrier.delivery.20260806carrier1@example.test';
test('carrier creates its Level 4 delivery employee',async({page})=>{
 test.setTimeout(90_000);
 await page.goto(`${baseURL}/login`);await page.locator('[name="email"]').fill(carrierEmail);await page.locator('[name="password"]').fill('OphyraQA!2026');await page.locator('form').filter({has:page.locator('[name="email"]')}).locator('button[type="submit"]').click();await expect(page).toHaveURL(/panel/);
 await page.goto(`${baseURL}/panel/planner-hub/institution-profile`);await page.locator('[name="business_nature"]').selectOption('logistics_delivery');await page.locator('[name="address_line1"]').fill('100 Logistics Avenue');await page.locator('[name="city"]').fill('Miami');await page.locator('[name="state"]').fill('FL');await page.locator('[name="zip"]').fill('33101');await page.locator('[name="short_description"]').fill('Certified Ophyra sandbox carrier.');await page.getByRole('button',{name:'Save Profile'}).click();await page.waitForLoadState('domcontentloaded');
 await page.goto(`${baseURL}/panel/planner-hub/management/users/create`);await page.getByRole('button',{name:'Start Creating User'}).click();await page.locator('.user-type-card[data-type="4"]').click();await page.locator('#emailInput').fill(deliveryEmail);await page.locator('#validateEmailBtn').click();await expect(page.locator('#mainFormCard')).toBeVisible({timeout:15000});await page.locator('#create-user-form [name="name"]').fill('Carrier');await page.locator('#create-user-form [name="lastname"]').fill('Driver');await page.locator('#create-user-form [name="phone"]').fill('+12025550177');await page.locator('#create-user-form [name="password"]').fill('OphyraQA!2026');await page.locator('#create-user-form [name="password_confirm"]').fill('OphyraQA!2026');await page.locator('[name="hourly_rate"]').fill('22');const roles=await page.locator('#role-select option').evaluateAll(o=>o.map(x=>x.value).filter(Boolean));await page.locator('#role-select').selectOption(roles[0]);await page.locator('#create-user-form button[type="submit"]').click();await page.waitForLoadState('domcontentloaded');
});
