const {test,expect}=require('@playwright/test');const{execFileSync}=require('child_process');const path=require('path');
const baseURL=process.env.E2E_BASE_URL||'http://localhost/ophyra';const password='OphyraQA!2026';
const sellerEmail='qa.seller.20260806cert1@example.test',driverEmail='qa.carrier.delivery.20260806cert1@example.test',clientEmail='qa.client.20260806cert1@example.test';
const sellerOwner='1642',packageCode='OPH-1642-11-01',qrToken='d7ff16b7d66ea7d365eaaa8fb3e570bbe2632641977ba1d4';
const proof={name:'evidence.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=','base64')};
async function login(page,email){await page.goto(`${baseURL}/login`);await page.locator('[name="email"]').fill(email);await page.locator('[name="password"]').fill(password);await page.locator('form').filter({has:page.locator('[name="email"]')}).locator('button[type="submit"]').click();await expect(page).toHaveURL(/panel/);}
test('marketplace package moves through carrier, absence, delivery and client tracking',async({browser},testInfo)=>{test.setTimeout(180000);
 execFileSync('php',[path.join(process.cwd(),'tests/support/reset_certification_package.php'),packageCode],{cwd:process.cwd()});
 const seller=await browser.newPage({viewport:{width:1440,height:900}});await login(seller,sellerEmail);
 // The client was created by the signup/association certification. Re-associate
 // imported marketplace orders idempotently so this physical-flow test can rerun.
 execFileSync('php',[path.join(process.cwd(),'tests/support/associate_certification_client.php'),clientEmail,sellerOwner],{cwd:process.cwd()});
 const driver=await browser.newPage({viewport:{width:390,height:844}});await login(driver,driverEmail);await driver.goto(`${baseURL}/panel/planner-hub/team/driver-mode`);await driver.locator('[name="package_code"]').fill(packageCode);await driver.locator('form').filter({has:driver.locator('[name="package_code"]')}).locator('button').click();await driver.waitForLoadState('domcontentloaded');
 await seller.goto(`${baseURL}/panel/planner-hub/store/orders/home`);const request=seller.locator('.carrier-request-alert').filter({hasText:packageCode});await expect(request).toBeVisible();await request.locator('button[value="APPROVE"]').click();await seller.waitForLoadState('domcontentloaded');
 const claim=await driver.request.post(`${baseURL}/panel/planner-hub/team/driver-mode`,{headers:{'X-Requested-With':'XMLHttpRequest','Accept':'application/json'},multipart:{action:'carrier_qr_claim',qr_token:qrToken,latitude:'25.7617',longitude:'-80.1918',qr_photo:proof}});expect(claim.ok()).toBeTruthy();const claimText=await claim.text();const payload=JSON.parse(claimText);expect(payload.success,claimText).toBeTruthy();const packageId=String(payload.package_id);
 async function stage(carrierStage,extra={}){const response=await driver.request.post(`${baseURL}/panel/planner-hub/team/driver-mode`,{headers:{'X-Requested-With':'XMLHttpRequest','Accept':'application/json'},multipart:{action:'carrier_advance',package_id:packageId,carrier_stage:carrierStage,notes:`Certification ${carrierStage}`,latitude:'25.7617',longitude:'-80.1918',evidence_photo:proof,...extra}});const text=await response.text();expect(response.ok(),text).toBeTruthy();const result=JSON.parse(text);expect(result.success,text).toBeTruthy();}
 await stage('received_hub');await stage('sorted_hub');await stage('out_for_delivery');await stage('customer_absent');
 const client=await browser.newPage({viewport:{width:1280,height:900}});await login(client,clientEmail);await client.goto(`${baseURL}/panel/store/orders/home?tab=incidents`);await expect(client.locator('body')).toContainText('#11');await expect(client.locator('body')).toContainText(/Delivery attempted|Intento de entrega|Tentativa de entrega/i);await client.screenshot({path:testInfo.outputPath('client-absence.png'),fullPage:true});
 await stage('out_for_delivery');await stage('delivered',{receiver_type:'BUYER',receiver_name:'QA Client',document_type:'CPF',document_number:'12345678900'});
 await seller.goto(`${baseURL}/panel/planner-hub/store/orders/home?package=${encodeURIComponent(packageCode)}`);await expect(seller.locator('.package-result')).toBeVisible();await expect(seller.locator('.package-timeline')).toContainText(/DELIVERED|delivered/i);await seller.screenshot({path:testInfo.outputPath('package-history.png'),fullPage:true});
 await client.goto(`${baseURL}/panel/store/orders/home?tab=closed`);await expect(client.locator('body')).toContainText(/Delivered|Entregada|Entregue/i);await client.screenshot({path:testInfo.outputPath('client-delivered.png'),fullPage:true});
 let row=client.locator('tr').filter({hasText:'#11'});await expect(row).toBeVisible();await row.locator('.request-return-btn').click();await client.locator('#requestReturnModal [name="return_notes"]').fill('Certification return after carrier delivery');await client.locator('#requestReturnModal .btn-danger').click();await expect(client).toHaveURL(/tab=incidents/);
 await seller.goto(`${baseURL}/panel/planner-hub/store/orders/home?tab=incidents`);row=seller.locator('tr').filter({hasText:'#11'});await expect(row).toBeVisible();await row.locator('.lifecycle-decision-btn').click();await seller.locator('#lifecycleDecisionSelect').selectOption('APPROVE');await seller.locator('#lifecycleDecisionForm .btn-primary').click();
 await seller.goto(`${baseURL}/panel/planner-hub/store/orders/home?tab=incidents`);row=seller.locator('tr').filter({hasText:'#11'});await row.locator('.lifecycle-decision-btn').click();await seller.locator('#lifecycleDecisionSelect').selectOption('RECEIVED_REFUND');await seller.locator('#lifecycleDecisionForm [name="decision_notes"]').fill('Return received and refunded by certification seller');await seller.locator('#lifecycleDecisionForm .btn-primary').click();await expect(seller).toHaveURL(/tab=closed/);await expect(seller.locator('tr').filter({hasText:'#11'})).toContainText(/Refunded|Reembolsado|Reembolsada/);
 await client.goto(`${baseURL}/panel/store/orders/home?tab=closed`);await expect(client.locator('tr').filter({hasText:'#11'})).toContainText(/Refunded|Reembolsado|Reembolsada/);await client.screenshot({path:testInfo.outputPath('client-return-refunded.png'),fullPage:true});
});
