const {test,expect}=require('@playwright/test');
const {execFileSync}=require('child_process');
const path=require('path');
const baseURL=process.env.E2E_BASE_URL||'http://localhost/ophytrak';
const email=process.env.E2E_SELLER_EMAIL||'qa.seller.20260806cert1@example.test';
const password='OphyraQA!2026';

async function signup(page){await page.goto(`${baseURL}/signup`);await page.locator('[name="company_name"]').fill('QA Omnichannel Seller');await page.locator('[data-signup-next]').click();await page.locator('[name="business_nature"]').selectOption('commerce_operations');await page.locator('[name="business_operation_type"]').selectOption('store_delivery_tracking');await page.locator('[data-signup-next]').click();await page.locator('[name="name"]').fill('QA');await page.locator('[name="lastname"]').fill('Seller');await page.locator('[name="email"]').fill(email);await page.locator('[name="phone_local_number"]').fill('3055550101');await page.locator('[data-signup-next]').click();await page.locator('[name="password"]').fill(password);await page.locator('[name="passwordConfirmation"]').fill(password);await page.locator('[name="terms"]').check();await page.locator('[data-signup-submit]').click();await expect(page.locator('[data-signup-success-modal]')).toHaveClass(/is-open/,{timeout:30000});}
async function login(page){await page.goto(`${baseURL}/login`);await page.locator('[name="email"]').fill(email);await page.locator('[name="password"]').fill(password);await page.locator('form').filter({has:page.locator('[name="email"]')}).locator('button[type="submit"]').click();await expect(page).toHaveURL(/panel/);}

test('Level 2 creates store and synchronizes Shopee, Mercado Libre and TikTok sandbox data',async({page},testInfo)=>{test.setTimeout(180000);
 await signup(page).catch(async()=>{await page.goto(`${baseURL}/login`);});
 execFileSync('php',[path.join(process.cwd(),'tests/support/activate_certification_modules.php'),email],{cwd:process.cwd()});
 await login(page);await page.goto(`${baseURL}/panel/planner-hub/institution-profile`);await page.locator('[name="business_nature"]').selectOption('commerce_operations');await page.locator('[name="address_line1"]').fill('500 Commerce Avenue');await page.locator('[name="city"]').fill('Miami');await page.locator('[name="state"]').fill('FL');await page.locator('[name="zip"]').fill('33101');await page.locator('[name="short_description"]').fill('Certified omnichannel sandbox store.');await page.getByRole('button',{name:'Save Profile'}).click();await page.waitForLoadState('domcontentloaded');
 await page.goto(`${baseURL}/panel/planner-hub/marketplace-connectors`);await expect(page.locator('body')).toContainText('Shopee Brasil');await expect(page.locator('body')).toContainText('Mercado Libre');await expect(page.locator('body')).toContainText('TikTok Shop');
 for(const provider of ['shopee_br','mercadolibre','tiktok_shop']){const form=page.locator(`form.connector-form input[name="provider"][value="${provider}"]`).locator('..');const card=page.locator('.connector-card').filter({has:page.locator(`input[name="provider"][value="${provider}"]`)});await card.locator('input[name="display_name"]').fill(`QA ${provider}`);await card.locator('input[name="account_id"]').fill(`QA-${provider}`);await card.locator('input[name="external_shop_id"]').fill(`QA-${provider}`);if(provider==='tiktok_shop')await card.locator('input[name="shop_cipher"]').fill('QA-CIPHER');await card.locator('input[name="access_token"]').fill('sandbox-token');await card.locator('input[name="is_active"]').check();await card.locator('button',{hasText:'Save connector'}).click();await page.waitForLoadState('domcontentloaded');const refreshed=page.locator('.connector-card').filter({has:page.locator(`input[name="provider"][value="${provider}"]`)});await refreshed.locator('button',{hasText:'Run Ophyra sandbox fixture'}).click();await page.waitForLoadState('domcontentloaded');}
 await page.goto(`${baseURL}/panel/planner-hub/store/orders/home`);await expect(page.locator('body')).toContainText(/Sandbox Customer/i);await expect(page.locator('body')).toContainText(/Paid|Pagado|Pago/i);await page.screenshot({path:testInfo.outputPath('marketplace-orders.png'),fullPage:true});
 await page.goto(`${baseURL}/panel/planner-hub/store/products/home`);await expect(page.locator('body')).toContainText(/Sandbox Product/i);await page.screenshot({path:testInfo.outputPath('marketplace-products.png'),fullPage:true});
});
