<?php
namespace App\Repositories;

class OphytrackPackageBillingRepository extends StoreRepository
{
    public function __construct(){ $this->table='ophytrack_package_charges';$this->db=new Connection(); }
    public function isReady():bool{$this->db->query("SELECT COUNT(*) total FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name=:table");$this->db->bind(':table',$this->table);return(int)($this->db->fetchOne()->total??0)===1;}
    private function cycle(?\DateTimeImmutable $at=null):array{$at=$at??new \DateTimeImmutable('now');$cut=max(1,min(28,(int)($_ENV['OPHYTRACK_USAGE_CUTOFF_DAY']??15)));$pay=max(1,min(28,(int)($_ENV['OPHYTRACK_USAGE_PAYMENT_DAY']??1)));if((int)$at->format('j')>$cut){$start=$at->setDate((int)$at->format('Y'),(int)$at->format('n'),$cut+1);$end=$at->modify('first day of next month')->setDate((int)$at->modify('first day of next month')->format('Y'),(int)$at->modify('first day of next month')->format('n'),$cut);}else{$start=$at->modify('first day of previous month')->setDate((int)$at->modify('first day of previous month')->format('Y'),(int)$at->modify('first day of previous month')->format('n'),$cut+1);$end=$at->setDate((int)$at->format('Y'),(int)$at->format('n'),$cut);}$due=$end->modify('first day of next month')->setDate((int)$end->modify('first day of next month')->format('Y'),(int)$end->modify('first day of next month')->format('n'),$pay);return[$start->format('Y-m-d'),$end->format('Y-m-d'),$due->format('Y-m-d')];}
    public function recordForCustody(object $package,int $carrierOwner):void{$this->record($package,$carrierOwner,null,'PLATFORM_USAGE',(float)($_ENV['OPHYTRACK_PACKAGE_FEE_BRL']??0));$rate=(float)($_ENV['OPHYTRACK_DEFAULT_CARRIER_PACKAGE_RATE_BRL']??0);if($rate>0)$this->record($package,(int)$package->id_owner,$carrierOwner,'CARRIER_SERVICE',$rate,$carrierOwner);}
    public function recordForOwnTeam(object $package):void{$this->record($package,(int)$package->id_owner,null,'PLATFORM_USAGE',(float)($_ENV['OPHYTRACK_PACKAGE_FEE_BRL']??0));$this->voidKind((int)$package->id,'CARRIER_SERVICE');}
    private function record(object $p,int $payer,?int $payee,string $kind,float $amount,?int $carrier=null):void{if(!$this->isReady()||$amount<=0)return;[$start,$end,$due]=$this->cycle();$this->db->query("INSERT INTO {$this->table} (id_store_package,id_store_order,seller_owner_id,carrier_owner_id,payer_owner_id,payee_owner_id,charge_kind,amount_brl,status,service_at,cycle_start,cycle_end,due_date,created_at,updated_at) VALUES (:package,:order,:seller,:carrier,:payer,:payee,:kind,:amount,'PENDING',NOW(),:start,:end,:due,NOW(),NOW()) ON DUPLICATE KEY UPDATE carrier_owner_id=VALUES(carrier_owner_id),payer_owner_id=VALUES(payer_owner_id),payee_owner_id=VALUES(payee_owner_id),amount_brl=VALUES(amount_brl),cycle_start=VALUES(cycle_start),cycle_end=VALUES(cycle_end),due_date=VALUES(due_date),status=IF(status='PAID','PAID','PENDING'),updated_at=NOW()");foreach([':package'=>(int)$p->id,':order'=>(int)$p->id_store_order,':seller'=>(int)$p->id_owner,':carrier'=>$carrier,':payer'=>$payer,':payee'=>$payee,':kind'=>$kind,':amount'=>$amount,':start'=>$start,':end'=>$end,':due'=>$due] as $k=>$v)$this->db->bind($k,$v);$this->db->execute();}
    private function voidKind(int $package,string $kind):void{if(!$this->isReady())return;$this->db->query("UPDATE {$this->table} SET status='VOID',updated_at=NOW() WHERE id_store_package=:package AND charge_kind=:kind AND status<>'PAID'");$this->db->bind(':package',$package);$this->db->bind(':kind',$kind);$this->db->execute();}
    public function forOwner(int $owner):array{if(!$this->isReady())return[];$this->db->query("SELECT c.*,sip.company_name seller_name,cip.company_name carrier_name FROM {$this->table} c LEFT JOIN institution_profile sip ON sip.id_owner=c.seller_owner_id LEFT JOIN institution_profile cip ON cip.id_owner=c.carrier_owner_id WHERE c.payer_owner_id=:owner OR c.payee_owner_id=:owner ORDER BY c.due_date,c.created_at");$this->db->bind(':owner',$owner);return$this->db->fetchAll();}
    public function summary(int $owner):array{$rows=$this->forOwner($owner);$s=['platform_due'=>0.0,'carrier_due'=>0.0,'receivable'=>0.0,'overdue'=>0.0];foreach($rows as $r){if(in_array($r->status,['PAID','VOID'],true))continue;$a=(float)$r->amount_brl;if((int)$r->payer_owner_id===$owner){if($r->charge_kind==='PLATFORM_USAGE')$s['platform_due']+=$a;else$s['carrier_due']+=$a;if($r->due_date<date('Y-m-d'))$s['overdue']+=$a;}if((int)$r->payee_owner_id===$owner)$s['receivable']+=$a;}return$s;}
    public function submitProof(int $id,int $payer,string $url,string $reference):bool{$this->db->query("UPDATE {$this->table} SET status='PROOF_SUBMITTED',payment_proof_url=:url,payment_reference=:reference,proof_submitted_at=NOW(),updated_at=NOW() WHERE id=:id AND payer_owner_id=:payer AND charge_kind='CARRIER_SERVICE' AND status='PENDING'");$this->db->bind(':url',$url);$this->db->bind(':reference',$reference?:null);$this->db->bind(':id',$id);$this->db->bind(':payer',$payer);$this->db->execute();return$this->db->rowCount()>0;}
    public function approveProof(int $id,int $payee):bool{$this->db->query("UPDATE {$this->table} SET status='PAID',paid_at=NOW(),updated_at=NOW() WHERE id=:id AND payee_owner_id=:payee AND charge_kind='CARRIER_SERVICE' AND status='PROOF_SUBMITTED'");$this->db->bind(':id',$id);$this->db->bind(':payee',$payee);$this->db->execute();return$this->db->rowCount()>0;}
}
