<?php
namespace App\Repositories;
class StoreOrdersRepository extends StoreRepository {
    public const PRICING_PAYG='PAYG'; public const PRICING_SUBSCRIPTION='SUBSCRIPTION'; public const PAYMENT_PENDING='PENDING'; public const PAYMENT_PAID='PAID'; public const PAYMENT_FAILED='FAILED'; public const PAYMENT_REFUNDED='REFUNDED'; public const STATUS_NEW='NEW'; public const STATUS_CONFIRMED='CONFIRMED'; public const STATUS_PROCESSING='PROCESSING'; public const STATUS_IN_PREPARATION='IN_PREPARATION'; public const STATUS_READY='READY'; public const STATUS_READY_FOR_DELIVERY='READY_FOR_DELIVERY'; public const STATUS_OUT_FOR_DELIVERY='OUT_FOR_DELIVERY'; public const STATUS_DELIVERY_ATTEMPTED='DELIVERY_ATTEMPTED'; public const STATUS_RETURNED_TO_BUSINESS='RETURNED_TO_BUSINESS'; public const STATUS_REDELIVERY_SCHEDULED='REDELIVERY_SCHEDULED'; public const STATUS_DELIVERED='DELIVERED'; public const STATUS_COMPLETED='COMPLETED'; public const STATUS_CANCELLED='CANCELLED'; public const STATUS_RETURN_REQUESTED='RETURN_REQUESTED'; public const STATUS_RETURN_APPROVED='RETURN_APPROVED'; public const STATUS_RETURN_REJECTED='RETURN_REJECTED'; public const STATUS_RETURNED='RETURNED'; public const STATUS_CLOSED='CLOSED';
    public function __construct(){ $this->table='store_orders';$this->db=new Connection(); }
    public function addCompatible(array $data): bool { return $this->add($this->filterExistingColumns($data)); }
    public function updateCompatible(array $data, array $criteria): bool { return $this->update($this->filterExistingColumns($data), $criteria); }
    public function generatePublicToken(): string { return bin2hex(random_bytes(24)); }
    public function getByPublicToken(string $token): ?object { $this->db->query("SELECT * FROM {$this->table} WHERE public_token=:token LIMIT 1");$this->db->bind(':token',$token);$row=$this->db->fetchOne();return $row?:null; }
    public function getById(int $id): ?object { return $this->getOne(['id'=>$id]); }
    public function getFullOrderDetails(int $id): ?object { $order=$this->getById($id);if($order)$order->items=(new StoreOrderItemsRepository())->getByOrder($id);return $order; }
    public function getAllByUser(int $id,int $limit=100): array { return $this->getLimited('id_user',$id,$limit); }
    public function getAllByGuestEmail(string $email,int $limit=100): array { return $this->getLimited('guest_email',$email,$limit); }
    public function getAllByClientWithCompany(int $userId, string $email = '', int $limit = 150): array {
        $sql = "SELECT so.*, ip.company_name, ip.logo_path AS company_logo_path, ip.email AS company_email, ip.phone AS company_phone, ip.address_line1 AS company_address_line1, ip.city AS company_city, ip.state AS company_state, ip.zip AS company_zip, ip.country AS company_country FROM {$this->table} so LEFT JOIN institution_profile ip ON ip.id_owner = so.id_owner WHERE so.id_user = :user";
        if ($email !== '') {
            $sql .= " OR so.guest_email = :email";
        }
        $sql .= " ORDER BY so.created_at DESC LIMIT {$limit}";
        $this->db->query($sql);
        $this->db->bind(':user', $userId);
        if ($email !== '') {
            $this->db->bind(':email', $email);
        }
        return $this->db->fetchAll();
    }
    public function getAllByOwner(int $owner,int $limit=300): array { return $this->getLimited('id_owner',$owner,$limit); }
    public function getByOwnerAndDateRange(int $owner,string $from,string $to,int $limit=300): array { $this->db->query("SELECT * FROM {$this->table} WHERE id_owner=:owner AND created_at BETWEEN :from AND :to ORDER BY created_at DESC LIMIT {$limit}");$this->db->bind(':owner',$owner);$this->db->bind(':from',$from);$this->db->bind(':to',$to);return $this->db->fetchAll(); }
    public function getHistoryByOwner(int $owner,string $from,string $to,int $limit=300): array { $this->db->query("SELECT * FROM {$this->table} WHERE id_owner=:owner AND created_at BETWEEN :from AND :to AND status IN ('DELIVERED','COMPLETED','DELIVERY_ATTEMPTED','RETURNED_TO_BUSINESS','REDELIVERY_SCHEDULED','RETURN_REQUESTED','RETURN_APPROVED','RETURN_REJECTED','RETURNED','CLOSED','CANCELLED') ORDER BY updated_at DESC, created_at DESC LIMIT {$limit}");$this->db->bind(':owner',$owner);$this->db->bind(':from',$from);$this->db->bind(':to',$to);return $this->db->fetchAll(); }
    public function markAsPaid(int $id): bool { return $this->update(['payment_status'=>self::PAYMENT_PAID,'updated_at'=>date('Y-m-d H:i:s')],['id'=>$id]); }
    public function markAsFailed(int $id): bool { return $this->update(['payment_status'=>self::PAYMENT_FAILED,'updated_at'=>date('Y-m-d H:i:s')],['id'=>$id]); }
    public function markAsRefunded(int $id): bool { return $this->update(['payment_status'=>self::PAYMENT_REFUNDED,'updated_at'=>date('Y-m-d H:i:s')],['id'=>$id]); }
    public function updateStatus(int $id,string $status): bool { $status=strtoupper(trim($status));if(!in_array($status,$this->statuses(),true))return false;$before=$this->getById($id);$ok=$this->update(['status'=>$status,'updated_at'=>date('Y-m-d H:i:s')],['id'=>$id]);if($ok&&$before){(new StorePackagesRepository())->recordStatus((int)$before->id_owner,$id,(string)$before->status,$status);}return $ok; }
    public function assignUser(int $id,int $user): bool { return $this->update(['id_user'=>$user,'updated_at'=>date('Y-m-d H:i:s')],['id'=>$id]); }
    public function requestReturn(int $id,string $notes): bool { $before=$this->getById($id);$ok=$this->updateCompatible(['status'=>self::STATUS_RETURN_REQUESTED,'return_notes'=>$notes,'return_requested_at'=>date('Y-m-d H:i:s'),'return_admin_message'=>null,'return_decision_at'=>null,'updated_at'=>date('Y-m-d H:i:s')],['id'=>$id]);if($ok&&$before)(new StorePackagesRepository())->recordStatus((int)$before->id_owner,$id,(string)$before->status,self::STATUS_RETURN_REQUESTED,null,$notes);return $ok; }
    public function reviewReturn(int $id,string $status,string $message=''): bool { $status=strtoupper(trim($status));if(!in_array($status,[self::STATUS_RETURN_APPROVED,self::STATUS_RETURN_REJECTED,self::STATUS_RETURNED,self::STATUS_REDELIVERY_SCHEDULED,self::STATUS_CLOSED],true))return false;$before=$this->getById($id);$ok=$this->updateCompatible(['status'=>$status,'return_admin_message'=>$message,'return_decision_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],['id'=>$id]);if($ok&&$before)(new StorePackagesRepository())->recordStatus((int)$before->id_owner,$id,(string)$before->status,$status,null,$message);return $ok; }
    public function closeReturn(int $id,string $message=''): bool { $before=$this->getById($id);$ok=$this->updateCompatible(['status'=>self::STATUS_CLOSED,'return_admin_message'=>$message,'return_closed_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],['id'=>$id]);if($ok&&$before)(new StorePackagesRepository())->recordStatus((int)$before->id_owner,$id,(string)$before->status,self::STATUS_CLOSED,null,$message);return $ok; }
    public function supportsCancellationWorkflow(): bool { return isset($this->getColumnMap()['cancellation_status']); }
    public function requestCancellation(int $id,string $reason,string $previousStatus): bool { if(!$this->supportsCancellationWorkflow())return false;return $this->updateCompatible(['cancellation_status'=>'REQUESTED','cancellation_reason'=>$reason,'cancellation_previous_status'=>$previousStatus,'cancellation_requested_at'=>date('Y-m-d H:i:s'),'cancellation_decision_at'=>null,'cancellation_admin_message'=>null,'updated_at'=>date('Y-m-d H:i:s')],['id'=>$id]); }
    public function resolveCancellation(int $id,string $decision,string $message='',string $nextStatus=''): bool { if(!$this->supportsCancellationWorkflow())return false;$decision=strtoupper(trim($decision));if(!in_array($decision,['REJECTED','RESEND','REFUNDED'],true))return false;$before=$this->getById($id);$data=['cancellation_status'=>$decision,'cancellation_admin_message'=>$message,'cancellation_decision_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')];if($nextStatus!=='')$data['status']=$nextStatus;$ok=$this->updateCompatible($data,['id'=>$id]);if($ok&&$before&&$nextStatus!==''&&$nextStatus!==(string)$before->status)(new StorePackagesRepository())->recordStatus((int)$before->id_owner,$id,(string)$before->status,$nextStatus,null,$message);return $ok; }
    public function statuses(): array { return [self::STATUS_NEW,self::STATUS_CONFIRMED,self::STATUS_PROCESSING,self::STATUS_IN_PREPARATION,self::STATUS_READY,self::STATUS_READY_FOR_DELIVERY,self::STATUS_OUT_FOR_DELIVERY,self::STATUS_DELIVERY_ATTEMPTED,self::STATUS_RETURNED_TO_BUSINESS,self::STATUS_REDELIVERY_SCHEDULED,self::STATUS_DELIVERED,self::STATUS_COMPLETED,self::STATUS_CANCELLED,self::STATUS_RETURN_REQUESTED,self::STATUS_RETURN_APPROVED,self::STATUS_RETURN_REJECTED,self::STATUS_RETURNED,self::STATUS_CLOSED]; }
    private function getLimited(string $field,mixed $value,int $limit): array { $this->db->query("SELECT * FROM {$this->table} WHERE {$field}=:value ORDER BY created_at DESC LIMIT {$limit}");$this->db->bind(':value',$value);return $this->db->fetchAll(); }
    private function filterExistingColumns(array $data): array { $columns=$this->getColumnMap(); if(!$columns)return $data; return array_filter($data, fn($key)=>isset($columns[$key]), ARRAY_FILTER_USE_KEY); }
    private function getColumnMap(): array { static $columns=null; if($columns!==null)return $columns; try{$this->db->query("SHOW COLUMNS FROM {$this->table}");$rows=$this->db->fetchAll();$columns=[];foreach($rows as $row){$columns[(string)$row->Field]=true;}return $columns;}catch(\Throwable $e){$columns=[];return $columns;} }
}
