<?php
namespace App\Repositories;
class StoreOrderWorkflowRepository extends StoreRepository {
    public function __construct(){ $this->table='store_order_workflow';$this->db=new Connection(); }
    public function getMapByOrders(array $orderIds): array { if(!$orderIds)return[];$ids=array_map('intval',$orderIds);$this->db->query("SELECT * FROM {$this->table} WHERE id_store_order IN (".implode(',',$ids).")");$rows=$this->db->fetchAll();$map=[];foreach($rows as $row)$map[(int)$row->id_store_order]=$row;return $map; }
    public function getByOrder(int $id): ?object { return $this->getOne(['id_store_order'=>$id]); }
    public function upsertAssignments(int $owner,int $order,?int $kitchen,?int $delivery): bool { $existing=$this->getByOrder($order);$data=['id_owner'=>$owner,'id_store_order'=>$order,'kitchen_user_id'=>$kitchen,'delivery_user_id'=>$delivery,'updated_at'=>date('Y-m-d H:i:s')];return $existing?$this->update($data,['id'=>(int)$existing->id]):$this->add($data+['created_at'=>date('Y-m-d H:i:s')]); }
    public function upsertOperations(int $owner,int $order,?int $kitchen,?int $delivery,bool $allowClose,bool $allowChat): bool { $existing=$this->getByOrder($order);$data=['id_owner'=>$owner,'id_store_order'=>$order,'kitchen_user_id'=>$kitchen,'delivery_user_id'=>$delivery,'allow_team_close_delivery'=>$allowClose?1:0,'allow_chat_with_client'=>$allowChat?1:0,'updated_at'=>date('Y-m-d H:i:s')];return $existing?$this->update($data,['id'=>(int)$existing->id]):$this->add($data+['created_at'=>date('Y-m-d H:i:s')]); }
    public function updateLatestLocation(int $order,int $user,float $lat,float $lng): bool { $existing=$this->getByOrder($order);if(!$existing)return false;return $this->update(['delivery_lat'=>$lat,'delivery_lng'=>$lng,'delivery_location_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],['id'=>(int)$existing->id]); }
    public function markDeliveryDispatch(int $order,int $user,?string $photo=null,?string $notes=null): bool { $existing=$this->getByOrder($order);if(!$existing)return false;$data=['delivery_notes'=>$notes,'sent_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')];if($photo!==null&&$photo!=='')$data['dispatch_photo_url']=$photo;return $this->update($data,['id'=>(int)$existing->id]); }
    public function markDeliveryProof(int $order,int $user,?string $photo=null,?string $notes=null,bool $completed=false,array $receiver=[]): bool { $existing=$this->getByOrder($order);if(!$existing)return false;$data=['delivery_notes'=>$notes,'delivery_closed_by'=>$user,'delivered_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')];if($photo!==null&&$photo!=='')$data['delivery_photo_url']=$photo;if($completed)$data['completed_at']=date('Y-m-d H:i:s');foreach(['delivery_receiver_type','delivery_receiver_name','delivery_document_type','delivery_document_number'] as $field){if(array_key_exists($field,$receiver))$data[$field]=trim((string)$receiver[$field]);}return $this->update($data,['id'=>(int)$existing->id]); }
    public function markManualStatusEvidence(int $order, int $user, ?string $photo = null, ?string $notes = null): bool { $existing=$this->getByOrder($order);if(!$existing)return false;$data=['delivery_notes'=>$notes,'delivery_closed_by'=>$user,'updated_at'=>date('Y-m-d H:i:s')];if($photo!==null&&$photo!=='')$data['delivery_photo_url']=$photo;return $this->update($data,['id'=>(int)$existing->id]); }
}
