-- Ophyra Affiliate / Referral Program alignment
-- Manual review required before execution.
-- This keeps affiliate status tied to the global user_id/id_user, not to level or business context.

CREATE TABLE IF NOT EXISTS affiliate_profiles (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    id_user INT NOT NULL,
    application_status ENUM('PENDING','APPROVED','REJECTED','SUSPENDED') NOT NULL DEFAULT 'PENDING',
    commission_rate DECIMAL(5,2) NOT NULL DEFAULT 30.00,
    legal_name VARCHAR(255) NULL,
    business_name VARCHAR(255) NULL,
    business_type VARCHAR(100) NULL,
    tax_country VARCHAR(100) NULL,
    tax_reference VARCHAR(100) NULL,
    tax_id_last4 VARCHAR(10) NULL,
    contact_email VARCHAR(255) NULL,
    contact_phone VARCHAR(50) NULL,
    address_line1 VARCHAR(255) NULL,
    city VARCHAR(100) NULL,
    state VARCHAR(100) NULL,
    zip VARCHAR(30) NULL,
    country VARCHAR(100) NULL,
    payout_method ENUM('PAYPAL','ACH','OTHER','MANUAL') NULL,
    paypal_email VARCHAR(255) NULL,
    account_holder_name VARCHAR(255) NULL,
    bank_name VARCHAR(255) NULL,
    routing_number TEXT NULL,
    routing_number_encrypted TEXT NULL,
    account_number_last4 VARCHAR(10) NULL,
    account_number_encrypted TEXT NULL,
    account_type VARCHAR(50) NULL,
    payout_notes TEXT NULL,
    reviewed_by INT NULL,
    reviewed_at DATETIME NULL,
    rejection_reason TEXT NULL,
    created_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY unique_affiliate_profile_user (id_user),
    KEY idx_affiliate_profiles_status (application_status),
    KEY idx_affiliate_profiles_commission_rate (commission_rate)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS affiliate_codes (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id INT NOT NULL,
    affiliate_code VARCHAR(50) NOT NULL,
    status ENUM('active','inactive','suspended') NOT NULL DEFAULT 'active',
    application_required TINYINT(1) NOT NULL DEFAULT 1,
    clicks INT NOT NULL DEFAULT 0,
    conversions INT NOT NULL DEFAULT 0,
    created_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY unique_affiliate_code (affiliate_code),
    UNIQUE KEY unique_affiliate_code_user (user_id),
    KEY idx_affiliate_code (affiliate_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS affiliate_referrals (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    referrer_id INT NOT NULL,
    referred_id INT NOT NULL,
    referred_business_id INT NULL,
    referral_code VARCHAR(50) NOT NULL,
    utm_source VARCHAR(100) NULL,
    utm_medium VARCHAR(100) NULL,
    utm_campaign VARCHAR(100) NULL,
    ip_address VARCHAR(45) NULL,
    user_agent TEXT NULL,
    cookie_id VARCHAR(120) NULL,
    status ENUM('pending','confirmed','cancelled') NOT NULL DEFAULT 'pending',
    confirmed_at DATETIME NULL,
    first_paid_at DATETIME NULL,
    last_paid_at DATETIME NULL,
    lifetime_gross_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    lifetime_commission_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    created_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY unique_referral (referrer_id, referred_id),
    KEY idx_referred_id (referred_id),
    KEY idx_referral_code (referral_code),
    KEY idx_affiliate_referrals_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS affiliate_commissions (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    referrer_id INT NOT NULL,
    referred_id INT NOT NULL,
    referral_id INT NOT NULL,
    transaction_type VARCHAR(60) NOT NULL,
    product_name VARCHAR(150) NULL,
    module_slug VARCHAR(100) NULL,
    transaction_id VARCHAR(190) NOT NULL,
    order_id INT NULL,
    payment_id INT NULL,
    payment_source_table VARCHAR(100) NULL,
    payment_source_id INT NULL,
    gross_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    payment_amount DECIMAL(12,2) NULL,
    payment_currency VARCHAR(10) NULL,
    commission_rate DECIMAL(5,2) NOT NULL DEFAULT 30.00,
    commission_percentage_snapshot DECIMAL(5,2) NULL,
    commission_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    commission_currency VARCHAR(10) NULL,
    currency VARCHAR(10) NULL DEFAULT 'USD',
    is_recurring TINYINT(1) NOT NULL DEFAULT 0,
    is_addon TINYINT(1) NOT NULL DEFAULT 1,
    eligible_for_commission TINYINT(1) NOT NULL DEFAULT 1,
    commission_period_year SMALLINT NULL,
    commission_period_month TINYINT NULL,
    status ENUM('pending','approved','payable','paid','rejected','reversed','adjusted','cancelled') NOT NULL DEFAULT 'pending',
    payment_method VARCHAR(50) NULL,
    paid_at DATETIME NULL,
    approved_at DATETIME NULL,
    cancelled_at DATETIME NULL,
    reversed_at DATETIME NULL,
    cancellation_reason TEXT NULL,
    payout_batch_id VARCHAR(100) NULL,
    notes TEXT NULL,
    created_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY unique_affiliate_commission_transaction (transaction_id),
    KEY idx_referrer_id (referrer_id),
    KEY idx_referred_id (referred_id),
    KEY idx_referral_id (referral_id),
    KEY idx_affiliate_commissions_status (status),
    KEY idx_affiliate_commissions_module_slug (module_slug),
    KEY idx_affiliate_commissions_payment_source (payment_source_table, payment_source_id),
    KEY idx_affiliate_commissions_period (commission_period_year, commission_period_month)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS affiliate_commission_payments (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    referrer_id INT NOT NULL,
    paid_by_user_id INT NULL,
    commission_ids TEXT NOT NULL,
    total_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    commission_count INT NOT NULL DEFAULT 0,
    payment_method VARCHAR(50) NULL,
    payout_method ENUM('PAYPAL','ACH','OTHER','MANUAL','CARD','STRIPE_CONNECT') NULL,
    payment_proof_url VARCHAR(255) NULL,
    payment_reference VARCHAR(150) NULL,
    payment_proof_original_name VARCHAR(255) NULL,
    payment_proof_mime VARCHAR(100) NULL,
    payment_proof_size INT NULL,
    stripe_transfer_id VARCHAR(150) NULL,
    payout_batch_id VARCHAR(100) NULL,
    status ENUM('pending','completed','failed','cancelled') NOT NULL DEFAULT 'completed',
    paid_at DATETIME NULL,
    payout_year SMALLINT NULL,
    payout_month TINYINT NULL,
    notes TEXT NULL,
    internal_notes TEXT NULL,
    external_notes TEXT NULL,
    created_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_affiliate_payments_referrer (referrer_id),
    KEY idx_payout_batch_id (payout_batch_id),
    KEY idx_affiliate_payments_period (payout_year, payout_month)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE affiliate_profiles
    ADD COLUMN IF NOT EXISTS routing_number_encrypted TEXT NULL AFTER routing_number,
    ADD COLUMN IF NOT EXISTS account_number_encrypted TEXT NULL AFTER account_number_last4;

ALTER TABLE affiliate_commissions
    ADD COLUMN IF NOT EXISTS payment_amount DECIMAL(12,2) NULL AFTER gross_amount,
    ADD COLUMN IF NOT EXISTS payment_currency VARCHAR(10) NULL AFTER payment_amount,
    ADD COLUMN IF NOT EXISTS commission_percentage_snapshot DECIMAL(5,2) NULL AFTER commission_rate,
    ADD COLUMN IF NOT EXISTS commission_currency VARCHAR(10) NULL AFTER commission_amount,
    MODIFY COLUMN status ENUM('pending','approved','payable','paid','rejected','reversed','adjusted','cancelled') NOT NULL DEFAULT 'pending';
