<?php

use App\Services\LoginService;
use App\Repositories\OphytrackDriverPayoutRepository;
use App\Repositories\CarrierPackageRepository;
use App\Services\UserWorkspaceContextService;
use App\Utils\TemplateResponse;
use App\Utils\Router;

$router = new Router();

$router->get(function (): string {
    $user = LoginService::getSession();
    $zone=new DateTimeZone('America/Sao_Paulo');$today=new DateTimeImmutable('today',$zone);$period=(string)($_GET['period']??'today');if(!in_array($period,['today','yesterday','current_fortnight','previous_fortnight','custom'],true))$period='today';
    $day=(int)$today->format('j');$currentStart=$day<=15?$today->modify('first day of this month'):$today->setDate((int)$today->format('Y'),(int)$today->format('m'),16);$currentEnd=$day<=15?$today->setDate((int)$today->format('Y'),(int)$today->format('m'),15):$today->modify('last day of this month');if($day>15){$previousStart=$today->modify('first day of this month');$previousEnd=$today->setDate((int)$today->format('Y'),(int)$today->format('m'),15);}else{$previousMonth=$today->modify('first day of previous month');$previousStart=$previousMonth->setDate((int)$previousMonth->format('Y'),(int)$previousMonth->format('m'),16);$previousEnd=$previousMonth->modify('last day of this month');}$periods=['today'=>[$today,$today],'yesterday'=>[$today->modify('-1 day'),$today->modify('-1 day')],'current_fortnight'=>[$currentStart,$currentEnd],'previous_fortnight'=>[$previousStart,$previousEnd]];if($period==='custom'){$customFrom=DateTimeImmutable::createFromFormat('!Y-m-d',(string)($_GET['from']??''),$zone);$customTo=DateTimeImmutable::createFromFormat('!Y-m-d',(string)($_GET['to']??''),$zone);if(!$customFrom||!$customTo){$period='today';[$from,$to]=$periods[$period];}else{$from=$customFrom;$to=$customTo;if($from>$to)[$from,$to]=[$to,$from];if($to>$today)$to=$today;if($from<$today->modify('-1 year'))$from=$today->modify('-1 year');}}else{[$from,$to]=$periods[$period];}
    $services=['amazon'=>'Amazon','avulso'=>'Avulso (remesa)','mercado_flex'=>'Mercado Envíos Flex','mercado_flex_turbo'=>'Mercado Envíos Flex Turbo','shopee'=>'Shopee','shopee_turbo'=>'Shopee Turbo','tracken_web'=>'Tracken web','vapt_magalu'=>'Vapt Magalu','vtex'=>'Vtex'];$selected=array_values(array_intersect(array_keys($services),(array)($_GET['services']??[])));$normalize=static function($row):string{$value=strtolower(trim((string)($row->order_source??'')).' '.trim((string)($row->payer_name??'')));if(str_contains($value,'amazon'))return'amazon';if(str_contains($value,'mercado')&&str_contains($value,'turbo'))return'mercado_flex_turbo';if(str_contains($value,'mercado'))return'mercado_flex';if((str_contains($value,'shopee')||str_contains($value,'shoppe'))&&str_contains($value,'turbo'))return'shopee_turbo';if(str_contains($value,'shopee')||str_contains($value,'shoppe'))return'shopee';if(str_contains($value,'magalu')||str_contains($value,'vapt'))return'vapt_magalu';if(str_contains($value,'vtex'))return'vtex';if(str_contains($value,'ophyra')||str_contains($value,'tracken'))return'tracken_web';return'avulso';};
    $payoutRepo=new OphytrackDriverPayoutRepository();$payouts=$payoutRepo->earningsForDriver((int)$user->getId(),$from->format('Y-m-d'),$to->format('Y-m-d'));foreach($payouts as $payout)$payout->service_key=$normalize($payout);if($selected)$payouts=array_values(array_filter($payouts,static fn($p)=>in_array($p->service_key,$selected,true)));if($period==='previous_fortnight')$payouts=array_values(array_filter($payouts,static fn($p)=>in_array((string)$p->status,['PENDING','PROOF_SUBMITTED','REJECTED'],true)));$deliveryTotal=array_reduce($payouts,static fn($sum,$p)=>$sum+(float)$p->amount_brl,0.0);
    $context=(new UserWorkspaceContextService())->getTeamContext($user);$owner=(int)($context['selectedOwnerId']??$user->getOwner());$collections=(new CarrierPackageRepository())->getCollectionHistory($owner,(int)$user->getId(),$from->format('Y-m-d'),$to->format('Y-m-d'));$collectionTotal=count($collections)*(float)($_ENV['OPHYTRACK_DEFAULT_COLLECTION_PAYOUT_BRL']??0);$adjustments=$payoutRepo->adjustmentsForDriver((int)$user->getId(),$owner,$from->format('Y-m-d'),$to->format('Y-m-d'));$credits=array_reduce($adjustments,static fn($sum,$a)=>$sum+((string)$a->adjustment_type==='CREDIT'?(float)$a->amount_brl:0),0.0);$debits=array_reduce($adjustments,static fn($sum,$a)=>$sum+((string)$a->adjustment_type==='DEBIT'?(float)$a->amount_brl:0),0.0);
    $companyBreakdown=[];foreach($payouts as $payout){$company=trim((string)($payout->payer_name??''))?:($services[$payout->service_key]??'Avulso (remesa)');if(!isset($companyBreakdown[$company]))$companyBreakdown[$company]=['name'=>$company,'count'=>0,'total'=>0.0];$companyBreakdown[$company]['count']++;$companyBreakdown[$company]['total']+=(float)$payout->amount_brl;}foreach($companyBreakdown as &$company){$company['rate']=$company['count']>0?$company['total']/$company['count']:0.0;}unset($company);usort($companyBreakdown,static fn($a,$b)=>strnatcasecmp($a['name'],$b['name']));
    return TemplateResponse::render(__DIR__.'/index.twig',['driverName'=>trim($user->getName().' '.$user->getLastname()),'driverCode'=>$user->getId(),'services'=>$services,'selectedServices'=>$selected,'period'=>$period,'periods'=>$periods,'from'=>$from,'to'=>$to,'deliveryCount'=>count($payouts),'deliveryTotal'=>$deliveryTotal,'collectionCount'=>count($collections),'collectionTotal'=>$collectionTotal,'adjustments'=>$adjustments,'credits'=>$credits,'debits'=>$debits,'receivable'=>$deliveryTotal+$collectionTotal+$credits-$debits,'companyBreakdown'=>$companyBreakdown,'queriedAt'=>new DateTimeImmutable('now',$zone)]);
});

$router->run();
