<?php
namespace App\Services\Marketplace;

use App\Repositories\Connection;
use App\Repositories\StorePackagesRepository;

final class MarketplaceImportService
{
    private Connection $db;
    public function __construct(){ $this->db=new Connection(); }
    public function importProducts(int $owner,object $connector,string $provider,array $products):int{$written=0;foreach($products as $p){if(!is_array($p)||empty($p['external_id']))continue;try{$this->db->beginTransaction();$productId=$this->mappedId($owner,$provider,'PRODUCT',(string)$p['external_id']);$data=$this->productData($owner,$p);if($productId){$this->update('store_products',$data,$productId);}else{$productId=$this->insert('store_products',$data);}$this->map($owner,(int)$connector->id,$provider,'PRODUCT',(string)$p['external_id'],'store_products',$productId,(string)($p['sku']??''),(string)($p['status']??''),$p);foreach((array)($p['variants']??[]) as $v){if(empty($v['external_id']))continue;$variantId=$this->mappedId($owner,$provider,'VARIANT',(string)$v['external_id']);$vd=['id_owner'=>$owner,'id_product'=>$productId,'name'=>(string)($v['name']?:$p['name']),'sku'=>(string)($v['sku']??''),'price'=>(float)($v['price']??0),'stock_quantity'=>(int)($v['stock']??0),'currency_code'=>(string)($p['currency']??'USD'),'status'=>'ACTIVE','updated_at'=>date('Y-m-d H:i:s')];if($variantId)$this->update('store_product_variations',$vd,$variantId);else$variantId=$this->insert('store_product_variations',$vd);$this->map($owner,(int)$connector->id,$provider,'VARIANT',(string)$v['external_id'],'store_product_variations',$variantId,(string)($v['sku']??''),'ACTIVE',$v,(string)$p['external_id']);}$this->db->commit();$written++;}catch(\Throwable $e){try{$this->db->rollback();}catch(\Throwable $ignored){}error_log('Marketplace product import: '.$e->getMessage());}}return $written;}
    public function importOrders(int $owner,object $connector,string $provider,array $orders):int{$written=0;foreach($orders as $o){if(!is_array($o)||empty($o['external_id']))continue;try{$this->db->beginTransaction();$orderId=$this->mappedId($owner,$provider,'ORDER',(string)$o['external_id']);$data=$this->orderData($owner,$provider,$connector,$o);if($orderId)$this->update('store_orders',$data,$orderId);else$orderId=$this->insert('store_orders',$data);$this->map($owner,(int)$connector->id,$provider,'ORDER',(string)$o['external_id'],'store_orders',$orderId,'',(string)($o['status']??''),$o);foreach((array)($o['items']??[]) as $line){$productId=$this->mappedId($owner,$provider,'PRODUCT',(string)($line['external_id']??''));$variantId=!empty($line['variant_id'])?$this->mappedId($owner,$provider,'VARIANT',(string)$line['variant_id']):null;if(!$productId)$productId=$this->placeholderProduct($owner,$provider,$line);$externalLine=(string)$o['external_id'].'|'.(string)($line['external_id']??'').'|'.(string)($line['variant_id']??'');$lineId=$this->mappedId($owner,$provider,'ORDER_ITEM',$externalLine);$qty=max(1,(int)($line['quantity']??1));$unit=(float)($line['unit_price']??0);$ld=['id_owner'=>$owner,'id_store_order'=>$orderId,'id_product'=>$productId,'id_product_variation'=>$variantId?:null,'external_item_id'=>(string)($line['external_id']??''),'external_variant_id'=>(string)($line['variant_id']??''),'seller_sku_snapshot'=>(string)($line['sku']??''),'product_name_snapshot'=>(string)($line['name']??'Marketplace product'),'variation_name_snapshot'=>null,'unit_price'=>$unit,'pricing_mode'=>'PAYG','quantity'=>$qty,'line_total'=>round($unit*$qty,2)];if($lineId)$this->update('store_order_items',$ld,$lineId);else$lineId=$this->insert('store_order_items',$ld);$this->map($owner,(int)$connector->id,$provider,'ORDER_ITEM',$externalLine,'store_order_items',$lineId,(string)($line['sku']??''),'IMPORTED',$line,(string)$o['external_id']);}$this->db->commit();try{(new StorePackagesRepository())->ensureForOrder($owner,$orderId);}catch(\Throwable $ignored){}$written++;}catch(\Throwable $e){try{$this->db->rollback();}catch(\Throwable $ignored){}error_log('Marketplace order import: '.$e->getMessage());}}return $written;}
    private function productData(int $owner,array $p):array{$name=trim((string)($p['name']??'Marketplace product'));$gallery=json_encode(array_values((array)($p['gallery']??[])),JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);return ['id_owner'=>$owner,'name'=>$name?:'Marketplace product','slug'=>strtolower(trim(preg_replace('/[^a-z0-9]+/i','-',$name),'-')).'-'.substr(hash('sha256',(string)$p['external_id']),0,8),'sku'=>(string)($p['sku']??''),'description'=>(string)($p['description']??''),'product_type'=>empty($p['variants'])?'FIXED':'VARIABLE','price'=>(float)($p['price']??0),'currency_code'=>(string)($p['currency']??'USD'),'main_image'=>$p['main_image']??null,'gallery'=>$gallery,'stock_quantity'=>(int)($p['stock']??0),'condition_code'=>(string)($p['condition']??''),'is_public'=>1,'status'=>$this->productStatus((string)($p['status']??'')),'marketplace_managed'=>1,'marketplace_updated_at'=>$this->date($p['updated_at']??null),'updated_at'=>date('Y-m-d H:i:s')];}
    private function orderData(int $owner,string $provider,object $connector,array $o):array{$c=$o['customer']??[];$s=$o['shipping']??[];$status=$this->orderStatus((string)($o['status']??''));$payment=$this->paymentStatus((string)($o['payment_status']??''),(float)($o['paid_amount']??0));return ['id_owner'=>$owner,'public_token'=>bin2hex(random_bytes(24)),'order_source'=>strtoupper($provider),'external_order_id'=>(string)$o['external_id'],'external_pack_id'=>(string)($o['pack_id']??''),'external_shipment_id'=>(string)($o['shipment_id']??''),'external_shop_id'=>(string)($connector->external_shop_id??$connector->account_id??''),'marketplace_updated_at'=>$this->date($o['updated_at']??null),'guest_name'=>trim((string)($c['name']??''))?:'Marketplace customer','guest_email'=>trim((string)($c['email']??''))?:('marketplace+'.preg_replace('/\W/','',(string)$o['external_id']).'@invalid.ophyra'),'guest_phone'=>(string)($c['phone']??''),'subtotal'=>(float)($o['total']??0),'discount'=>0,'total'=>(float)($o['total']??0),'payment_status'=>$payment,'status'=>$status,'pricing_mode'=>'PAYG','shipping_address_1'=>(string)($s['address1']??''),'shipping_address_2'=>(string)($s['address2']??''),'shipping_city'=>(string)($s['city']??''),'shipping_state'=>(string)($s['state']??''),'shipping_zip'=>(string)($s['zip']??''),'shipping_country'=>(string)($s['country']??''),'items_count'=>count((array)($o['items']??[])),'meals_count'=>array_sum(array_column((array)($o['items']??[]),'quantity')),'updated_at'=>date('Y-m-d H:i:s')];}
    private function mappedId(int $owner,string $provider,string $type,string $external):?int{if($external==='')return null;$this->db->query('SELECT internal_id FROM marketplace_resource_mappings WHERE id_owner=:owner AND provider=:provider AND resource_type=:type AND external_id=:external LIMIT 1');foreach(['owner'=>$owner,'provider'=>$provider,'type'=>$type,'external'=>$external]as$k=>$v)$this->db->bind(':'.$k,$v);$r=$this->db->fetchOne();return $r?(int)$r->internal_id:null;}
    private function map(int $owner,int $connector,string $provider,string $type,string $external,string $table,int $internal,string $sku,string $status,array $raw,string $parent=''):void{$this->db->query('INSERT INTO marketplace_resource_mappings(id_owner,connector_id,provider,resource_type,external_id,external_parent_id,internal_table,internal_id,external_sku,external_status,checksum,raw_payload,last_seen_at) VALUES(:owner,:connector,:provider,:type,:external,:parent,:table_name,:internal,:sku,:status,:checksum,:raw,NOW()) ON DUPLICATE KEY UPDATE internal_table=VALUES(internal_table),internal_id=VALUES(internal_id),external_parent_id=VALUES(external_parent_id),external_sku=VALUES(external_sku),external_status=VALUES(external_status),checksum=VALUES(checksum),raw_payload=VALUES(raw_payload),last_seen_at=NOW(),updated_at=NOW()');$json=json_encode($raw,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);foreach(['owner'=>$owner,'connector'=>$connector,'provider'=>$provider,'type'=>$type,'external'=>$external,'parent'=>$parent?:null,'table_name'=>$table,'internal'=>$internal,'sku'=>$sku?:null,'status'=>$status?:null,'checksum'=>hash('sha256',$json),'raw'=>$json]as$k=>$v)$this->db->bind(':'.$k,$v);$this->db->execute();}
    private function insert(string $table,array $data):int{$cols=array_keys($data);$this->db->query('INSERT INTO '.$table.' (`'.implode('`,`',$cols).'`) VALUES (:'.implode(',:',$cols).')');foreach($data as$k=>$v)$this->db->bind(':'.$k,$v);$this->db->execute();return(int)$this->db->lastId();}
    private function update(string $table,array $data,int $id):void{if($table==='store_orders')unset($data['public_token']);$set=implode(',',array_map(fn($k)=>'`'.$k.'`=:'.$k,array_keys($data)));$this->db->query('UPDATE '.$table.' SET '.$set.' WHERE id=:record_id');foreach($data as$k=>$v)$this->db->bind(':'.$k,$v);$this->db->bind(':record_id',$id);$this->db->execute();}
    private function placeholderProduct(int $owner,string $provider,array $line):int{$sku=trim((string)($line['sku']??''));if($sku!==''){$this->db->query('SELECT id FROM store_products WHERE id_owner=:owner AND sku=:sku LIMIT 1');$this->db->bind(':owner',$owner);$this->db->bind(':sku',$sku);$found=$this->db->fetchOne();if($found)return(int)$found->id;}$p=['external_id'=>(string)($line['external_id']??hash('sha256',json_encode($line))),'sku'=>$sku,'name'=>(string)($line['name']??'Marketplace product'),'price'=>(float)($line['unit_price']??0),'currency'=>'BRL','stock'=>0,'status'=>'ACTIVE','variants'=>[]];return$this->insert('store_products',$this->productData($owner,$p));}
    private function productStatus(string $s):string{return in_array(strtoupper($s),['ACTIVE','NORMAL','ACTIVATE','LIVE'],true)?'ACTIVE':(in_array(strtoupper($s),['DRAFT','PENDING','UNDER_REVIEW'],true)?'DRAFT':'INACTIVE');}
    private function paymentStatus(string $s,float $paid):string{$s=strtoupper($s);return $paid>0||in_array($s,['PAID','APPROVED','CAPTURED','COMPLETED'],true)?'PAID':(in_array($s,['REFUNDED','REFUND'],true)?'REFUNDED':'PENDING');}
    private function orderStatus(string $s):string{$s=strtoupper($s);return match(true){str_contains($s,'CANCEL')=>'CANCELLED',str_contains($s,'DELIVER')||$s==='COMPLETED'=>'DELIVERED',str_contains($s,'SHIP')||str_contains($s,'TRANSIT')=>'OUT_FOR_DELIVERY',str_contains($s,'READY')=>'READY_FOR_DELIVERY',str_contains($s,'PROCESS')||str_contains($s,'PREPAR')=>'IN_PREPARATION',default=>'NEW'};}
    private function date(mixed $v):?string{if(!$v)return null;$t=is_numeric($v)?(int)$v:strtotime((string)$v);return$t?date('Y-m-d H:i:s',$t):null;}
}
