<?php
namespace App\Services\Marketplace;

final class ShopeeProvider implements MarketplaceProviderInterface
{
    private string $base='https://partner.shopeemobile.com';
    public function __construct(private object $connector,private MarketplaceHttpClient $http=new MarketplaceHttpClient()){}
    public function provider():string{return 'shopee_br';}
    private function call(string $path,array $query=[]):array{$partner=(int)($_ENV['SHOPEE_PARTNER_ID']??0);$key=(string)($_ENV['SHOPEE_PARTNER_KEY']??'');$shop=(int)($this->connector->external_shop_id??$this->connector->account_id??0);if($partner<=0||$key===''||$shop<=0)throw new \RuntimeException('Shopee Partner credentials and shop ID are required.');$ts=time();$sign=hash_hmac('sha256',$partner.$path.$ts.$this->connector->access_token.$shop,$key);$query=array_merge($query,['partner_id'=>$partner,'timestamp'=>$ts,'access_token'=>$this->connector->access_token,'shop_id'=>$shop,'sign'=>$sign]);$r=$this->http->request('GET',$this->base.$path.'?'.http_build_query($query))['data'];if(!empty($r['error']))throw new \RuntimeException('Shopee: '.($r['message']??$r['error']));return $r;}
    public function testConnection():array{$r=$this->call('/api/v2/shop/get_shop_info');return ['success'=>true,'shop_id'=>(string)($r['shop_id']??$this->connector->external_shop_id??''),'name'=>$r['shop_name']??'Shopee Brasil'];}
    public function fetchProducts(?string $cursor=null):array{$offset=max(0,(int)$cursor);$list=$this->call('/api/v2/product/get_item_list',['offset'=>$offset,'page_size'=>50,'item_status'=>'NORMAL']);$brief=(array)($list['response']['item']??[]);$ids=array_map(fn($x)=>(string)$x['item_id'],$brief);$products=[];if($ids){$detail=$this->call('/api/v2/product/get_item_base_info',['item_id_list'=>implode(',',$ids)]);foreach((array)($detail['response']['item_list']??[]) as $p)$products[]=$this->product($p);}return ['items'=>$products,'next_cursor'=>!empty($list['response']['has_next_page'])?(string)($list['response']['next_offset']??($offset+50)):null,'raw_count'=>count($products)];}
    public function fetchOrders(?string $cursor=null):array{$from=$cursor?max(0,(int)$cursor):time()-86400*15;$list=$this->call('/api/v2/order/get_order_list',['time_range_field'=>'update_time','time_from'=>$from,'time_to'=>time(),'page_size'=>50]);$brief=(array)($list['response']['order_list']??[]);$sns=array_map(fn($x)=>(string)$x['order_sn'],$brief);$orders=[];$latest=$from;if($sns){$detail=$this->call('/api/v2/order/get_order_detail',['order_sn_list'=>implode(',',$sns),'response_optional_fields'=>'buyer_user_id,buyer_username,recipient_address,item_list,total_amount,currency,payment_method,shipping_carrier,package_list']);foreach((array)($detail['response']['order_list']??[]) as $o){$orders[]=$this->order($o);$latest=max($latest,(int)($o['update_time']??0));}}return ['items'=>$orders,'next_cursor'=>(string)$latest,'raw_count'=>count($orders)];}
    private function product(array $p):array{$images=(array)($p['image']['image_url_list']??[]);return ['external_id'=>(string)($p['item_id']??''),'sku'=>(string)($p['item_sku']??''),'name'=>(string)($p['item_name']??''),'description'=>(string)($p['description']??''),'price'=>(float)($p['price_info'][0]['current_price']??$p['price_info'][0]['original_price']??0),'currency'=>'BRL','stock'=>(int)($p['stock_info_v2']['summary_info']['total_available_stock']??0),'status'=>(string)($p['item_status']??''),'condition'=>(string)($p['condition']??''),'main_image'=>$images[0]??null,'gallery'=>$images,'variants'=>[],'updated_at'=>isset($p['update_time'])?date('Y-m-d H:i:s',(int)$p['update_time']):null,'raw'=>$p];}
    private function order(array $o):array{$a=$o['recipient_address']??[];return ['external_id'=>(string)($o['order_sn']??''),'pack_id'=>(string)($o['package_list'][0]['package_number']??''),'shipment_id'=>(string)($o['package_list'][0]['logistics_status']??''),'status'=>(string)($o['order_status']??''),'payment_status'=>(string)($o['payment_method']??''),'currency'=>(string)($o['currency']??'BRL'),'total'=>(float)($o['total_amount']??0),'paid_amount'=>(float)($o['total_amount']??0),'customer'=>['external_id'=>(string)($o['buyer_user_id']??''),'name'=>(string)($a['name']??$o['buyer_username']??''),'email'=>'','phone'=>(string)($a['phone']??'')],'shipping'=>['address1'=>(string)($a['full_address']??''),'address2'=>'','city'=>(string)($a['city']??''),'state'=>(string)($a['state']??''),'zip'=>(string)($a['zipcode']??''),'country'=>(string)($a['region']??'BR')],'items'=>array_map(fn($i)=>['external_id'=>(string)($i['item_id']??''),'variant_id'=>(string)($i['model_id']??''),'sku'=>(string)($i['model_sku']??$i['item_sku']??''),'name'=>(string)($i['item_name']??''),'quantity'=>(int)($i['model_quantity_purchased']??1),'unit_price'=>(float)($i['model_discounted_price']??$i['model_original_price']??0)],(array)($o['item_list']??[])),'updated_at'=>isset($o['update_time'])?date('Y-m-d H:i:s',(int)$o['update_time']):null,'raw'=>$o];}
}
