<?php
namespace App\Services\Marketplace;

final class TikTokShopProvider implements MarketplaceProviderInterface
{
    private string $base='https://open-api.tiktokglobalshop.com';
    public function __construct(private object $connector,private MarketplaceHttpClient $http=new MarketplaceHttpClient()){}
    public function provider(): string{return 'tiktok_shop';}
    private function call(string $method,string $path,array $query=[],?array $body=null): array{
        $key=(string)($_ENV['TIKTOK_SHOP_APP_KEY']??'');$secret=(string)($_ENV['TIKTOK_SHOP_APP_SECRET']??'');if($key===''||$secret==='')throw new \RuntimeException('TikTok Shop app credentials are not configured.');
        $query=array_merge($query,['app_key'=>$key,'timestamp'=>time(),'shop_cipher'=>(string)($this->connector->shop_cipher??'')]);ksort($query);$base=$path;foreach($query as $k=>$v){if($k!=='sign'&&$k!=='access_token')$base.=$k.$v;}$rawBody=$body!==null?json_encode($body,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE):'';$query['sign']=hash_hmac('sha256',$secret.$base.$rawBody.$secret,$secret);
        return $this->http->request($method,$this->base.$path.'?'.http_build_query($query),['content-type: application/json','x-tts-access-token: '.$this->connector->access_token],$body)['data'];
    }
    public function testConnection(): array{$r=$this->call('GET','/authorization/202309/shops',[],null);$shop=$r['data']['shops'][0]??$r['data']['shop_list'][0]??null;return ['success'=>(bool)$shop,'shop_id'=>(string)($shop['id']??$shop['shop_id']??''),'name'=>$shop['name']??$shop['shop_name']??'TikTok Shop'];}
    public function fetchProducts(?string $cursor=null): array{$body=['page_size'=>50];if($cursor)$body['page_token']=$cursor;$r=$this->call('POST','/product/202309/products/search',[],$body);$data=$r['data']??[];$products=[];foreach((array)($data['products']??[]) as $p){$products[]=$this->product($p);}$next=$data['next_page_token']??null;return ['items'=>$products,'next_cursor'=>$next?:null,'raw_count'=>count($products)];}
    public function fetchOrders(?string $cursor=null): array{$body=['page_size'=>50,'sort_order'=>'ASC'];if($cursor)$body['update_time_from']=max(0,(int)$cursor);else $body['create_time_from']=time()-86400*30;$r=$this->call('POST','/order/202309/orders/search',[],$body);$orders=[];$latest=(int)($cursor?:0);foreach((array)($r['data']['orders']??[]) as $o){$orders[]=$this->order($o);$latest=max($latest,(int)($o['update_time']??0));}return ['items'=>$orders,'next_cursor'=>(string)$latest,'raw_count'=>count($orders)];}
    private function product(array $p):array{$skus=(array)($p['skus']??[]);$first=$skus[0]??[];$images=array_map(fn($x)=>$x['urls'][0]??$x['url']??null,(array)($p['main_images']??[]));return ['external_id'=>(string)($p['id']??''),'sku'=>(string)($first['seller_sku']??''),'name'=>(string)($p['title']??''),'description'=>(string)($p['description']??''),'price'=>(float)($first['price']['sale_price']??$first['price']['tax_exclusive_price']??0),'currency'=>(string)($first['price']['currency']??'BRL'),'stock'=>(int)($first['inventory'][0]['quantity']??0),'status'=>(string)($p['status']??''),'condition'=>(string)($p['product_type']??''),'main_image'=>$images[0]??null,'gallery'=>array_values(array_filter($images)),'variants'=>array_map(fn($v)=>['external_id'=>(string)($v['id']??''),'sku'=>(string)($v['seller_sku']??''),'name'=>implode(' / ',array_map(fn($s)=>$s['value_name']??'',(array)($v['sales_attributes']??[]))),'price'=>(float)($v['price']['sale_price']??$v['price']['tax_exclusive_price']??0),'stock'=>(int)($v['inventory'][0]['quantity']??0)],$skus),'updated_at'=>isset($p['update_time'])?date('Y-m-d H:i:s',(int)$p['update_time']):null,'raw'=>$p];}
    private function order(array $o):array{$recipient=$o['recipient_address']??[];return ['external_id'=>(string)($o['id']??''),'pack_id'=>(string)($o['packages'][0]['id']??''),'shipment_id'=>(string)($o['packages'][0]['tracking_number']??''),'status'=>(string)($o['status']??''),'payment_status'=>(string)($o['payment']['payment_status']??$o['payment_status']??''),'currency'=>(string)($o['payment']['currency']??'BRL'),'total'=>(float)($o['payment']['total_amount']??0),'paid_amount'=>(float)($o['payment']['total_amount']??0),'customer'=>['external_id'=>(string)($o['buyer_user_id']??''),'name'=>(string)($recipient['name']??''),'email'=>(string)($o['buyer_email']??''),'phone'=>(string)($recipient['phone_number']??'')],'shipping'=>['address1'=>(string)($recipient['full_address']??$recipient['address_line1']??''),'address2'=>(string)($recipient['address_line2']??''),'city'=>(string)($recipient['city']??''),'state'=>(string)($recipient['state']??''),'zip'=>(string)($recipient['postal_code']??''),'country'=>(string)($recipient['region_code']??'BR')],'items'=>array_map(fn($i)=>['external_id'=>(string)($i['product_id']??''),'variant_id'=>(string)($i['sku_id']??''),'sku'=>(string)($i['seller_sku']??''),'name'=>(string)($i['product_name']??''),'quantity'=>(int)($i['quantity']??1),'unit_price'=>(float)($i['sale_price']??$i['original_price']??0)],(array)($o['line_items']??[])),'updated_at'=>isset($o['update_time'])?date('Y-m-d H:i:s',(int)$o['update_time']):null,'raw'=>$o];}
}
